### ISSUE TITLE
west Garden is listed twice

### ISSUE THREAD

**Issue by CalebCrosbySears** [aknobloch/An-Endless-Night#56]
Where would you like to move to?
0. Stay here
1. West Garden
2. West Garden
this happens when trying to move out of the northwest shed.

**Comment by aknobloch** [comment]
Alright cool I'll check it out as soon as I'm done with my chemistry homework

**Comment by aknobloch** [comment]
So this is because there are multiple doors that lead to the same place. That is how it's described in the requirements documentation. I see two possible solutions. One, say screw the requirements documentation and delete any cases where multiple doors go to the same place. I don't want to do that, I'd rather stick to the reqts as much as possible. So the only other solution is add door descriptions. These are described in the reqts but for some reason they were never added into the actual door entity objects. this would be the best option imo because then we stick to the reqts and can output door desciptions. I.E 

"Where would you like to move?"
"1. An old staircase to the West Garden"
"2. A sliding door to the West Garden"

Either way it's stupid design to have multiple doors leading to the same place....but that's what the reqts say.

**Comment by EstephanieGonzalez** [comment]
pushed changes, shouldn't give issues anymore
